/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.desktop.DesktopApp.UI;

import com.desktop.DesktopApp.Repository.CursoRepository;
import com.desktop.DesktopApp.Repository.HorarioRepository;
import com.desktop.DesktopApp.Repository.MateriaRepository;
import com.desktop.DesktopApp.Repository.ProfesorRepository;

import javax.swing.*;

/**
 *
 * @author Juan
 */
public class Administracion extends javax.swing.JFrame {
    private MateriaRepository materiaRepository;
    private CursoRepository cursoRepository;
    private HorarioRepository horarioRepository;
    private ProfesorRepository profesorRepository;

    /**
     * Creates new form Administracion
     */
    public Administracion(CursoRepository cursoRepository, MateriaRepository materiaRepository,
                          HorarioRepository horarioRepository, ProfesorRepository profesorRepository) {
        this.cursoRepository = cursoRepository;
        this.horarioRepository = horarioRepository;
        this.materiaRepository = materiaRepository;
        this.profesorRepository = profesorRepository;
        initComponents();
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        horarioButton = new javax.swing.JButton();
        materiaButton = new javax.swing.JButton();
        cursoButton = new javax.swing.JButton();
        asignarProfesorButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("  ");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(27, 28, 49));
        jPanel1.setForeground(new java.awt.Color(27, 28, 49));

        horarioButton.setBackground(new java.awt.Color(49, 49, 84));
        horarioButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        horarioButton.setForeground(new java.awt.Color(255, 255, 255));
        horarioButton.setText("Crear horario");
        horarioButton.setBorder(null);
        horarioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                horarioButtonActionPerformed(evt);
            }
        });

        materiaButton.setBackground(new java.awt.Color(49, 49, 84));
        materiaButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        materiaButton.setForeground(new java.awt.Color(255, 255, 255));
        materiaButton.setText("Crear materia");
        materiaButton.setBorder(null);
        materiaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materiaButtonActionPerformed(evt);
            }
        });

        cursoButton.setBackground(new java.awt.Color(49, 49, 84));
        cursoButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cursoButton.setForeground(new java.awt.Color(255, 255, 255));
        cursoButton.setText("Crear curso");
        cursoButton.setBorder(null);
        cursoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cursoButtonActionPerformed(evt);
            }
        });

        asignarProfesorButton.setBackground(new java.awt.Color(49, 49, 84));
        asignarProfesorButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        asignarProfesorButton.setForeground(new java.awt.Color(255, 255, 255));
        asignarProfesorButton.setText("Asignar profesor");
        asignarProfesorButton.setBorder(null);
        asignarProfesorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asignarProfesorButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cursoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(materiaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(horarioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(asignarProfesorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(160, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(213, 213, 213)
                .addComponent(cursoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(materiaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(horarioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(asignarProfesorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(244, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cursoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cursoButtonActionPerformed
        CrearCurso crearCurso = new CrearCurso(cursoRepository);
    }//GEN-LAST:event_cursoButtonActionPerformed

    private void materiaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materiaButtonActionPerformed
        CrearMateria crearMateria = new CrearMateria(materiaRepository, cursoRepository);
    }//GEN-LAST:event_materiaButtonActionPerformed

    private void horarioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_horarioButtonActionPerformed
        CrearHorario crearHorario = new CrearHorario(materiaRepository, horarioRepository);
    }//GEN-LAST:event_horarioButtonActionPerformed

    private void asignarProfesorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asignarProfesorButtonActionPerformed
        AsignarProfesor asignarProfesor = new AsignarProfesor(profesorRepository, materiaRepository);
    }//GEN-LAST:event_asignarProfesorButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton asignarProfesorButton;
    private javax.swing.JButton cursoButton;
    private javax.swing.JButton horarioButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton materiaButton;
    // End of variables declaration//GEN-END:variables
}
