/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.desktop.DesktopApp.UI;

import com.desktop.DesktopApp.Entity.*;
import com.desktop.DesktopApp.Repository.UsuarioRepository;
import com.desktop.DesktopApp.Swing.BoletinTableModel;

import javax.swing.*;
import java.awt.Color;

/**
 *
 * @author Juan
 */
public class Boletin extends javax.swing.JFrame {

    private EstudianteEntity estudiante;
    private UsuarioRepository usuarioRepository;
    private BoletinTableModel boletinTableModel = new BoletinTableModel();

    /**
     * Creates new form Boletin
     */
    public Boletin(Long usuarioId, UsuarioRepository usuarioRepository) {
        initComponents();
        this.usuarioRepository = usuarioRepository;
        UsuarioEntity usuario = usuarioRepository.findById(usuarioId).orElseThrow();
        jTable1.getTableHeader().setBackground(new Color(32,136,203));
        
        
        if (usuario.getRol().equals(Roles.Titular)) {
            TitularEntity titular = (TitularEntity) usuario;
            estudiante = titular.getHijo();
        } else {
            estudiante = (EstudianteEntity) usuario;
        }
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        cargarTabla();
        this.setVisible(true);
    }

    private void cargarTabla() {
        if(estudiante == null || estudiante.getCurso() == null || estudiante.getCalificaciones() == null){
            JOptionPane.showMessageDialog(null, "Error al cargar la tabla, faltan datos");
        }
        else{


        for (MateriaEntity materia: estudiante.getCurso().getMaterias()) {
            String notas = "";
            for (CalificacionEntity calificacion: estudiante.getCalificaciones()) {
                if (calificacion.getMateria().getNombre().equals(materia.getNombre())) {
                    notas += calificacion.getDescripcion() + ": " + calificacion.getNota();
                }
                if (calificacion.getMateria().getNombre().equals(materia.getNombre()) && estudiante.getCalificaciones().indexOf(calificacion) < estudiante.getCalificaciones().size() - 1) {
                    notas += ", ";
                }
            }
            boletinTableModel.addRow(new Object[] {materia.getNombre(), notas});
        }
        jTable1.setModel(boletinTableModel);
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(" ");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(13, 14, 35));

        label1.setBackground(new java.awt.Color(13, 14, 35));
        label1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label1.setForeground(new java.awt.Color(204, 204, 204));
        label1.setText("Boletín");

        jTable1.setBackground(new java.awt.Color(27, 28, 49));
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setToolTipText("");
        jTable1.setFocusable(false);
        jTable1.setGridColor(new java.awt.Color(59, 60, 91));
        jTable1.setSelectionForeground(new java.awt.Color(204, 204, 204));
        jTable1.setShowGrid(false);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 621, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables
}
