/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.desktop.DesktopApp.UI;

import com.desktop.DesktopApp.Entity.UsuarioEntity;
import com.desktop.DesktopApp.Repository.*;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author Juan
 */
public class Dashboard extends javax.swing.JFrame {

    private UsuarioEntity usuario;
    private EstudianteRepository estudianteRepository;
    private ProfesorRepository profesorRepository;
    private UsuarioRepository usuarioRepository;
    private CursoRepository cursoRepository;
    private PagoRepository pagoRepository;
    private TitularRepository titularRepository;
    private MateriaRepository materiaRepository;
    private HorarioRepository horarioRepository;

    /**
     * Creates new form Dashboard
     */
    public Dashboard(UsuarioEntity usuario, EstudianteRepository estudianteRepository, ProfesorRepository profesorRepository,
                     UsuarioRepository usuarioRepository, CursoRepository cursoRepository,
                     PagoRepository pagoRepository, TitularRepository titularRepository,
                     MateriaRepository materiaRepository, HorarioRepository horarioRepository) {
        this.pagoRepository = pagoRepository;
        this.usuario = usuario;
        this.estudianteRepository = estudianteRepository;
        this.profesorRepository = profesorRepository;
        this.usuarioRepository = usuarioRepository;
        this.cursoRepository = cursoRepository;
        this.titularRepository = titularRepository;
        this.materiaRepository = materiaRepository;
        this.horarioRepository = horarioRepository;

        initComponents();

        // Obtiene la resolución de pantalla actual.
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();

        // Establece el tamaño del JFrame al tamaño de la pantalla.
        this.setSize(screenSize);

        this.setExtendedState(this.getExtendedState() | JFrame.MAXIMIZED_BOTH);

        ocultarBotones();

        this.setVisible(true);
    }

    private void ocultarBotones() {
        switch (this.usuario.getRol().toString()) {
            case "Admin":
                CuotaButton.setVisible(false);
                BoletinButton.setVisible(false);
                HorarioButton.setVisible(false);
                break;
            case "Personal":
                BoletinButton.setVisible(false);
                HorarioButton.setVisible(false);
                break;
            case "Profesor":
                InformesButton1.setVisible(false);
                BoletinButton.setVisible(false);
                CuotaButton.setVisible(false);
                administracionButton.setVisible(false);
                break;
            case "Estudiante":
                administracionButton.setVisible(false);
                InformesButton1.setVisible(false);
                CuotaButton.setVisible(false);
                AlumnoButton.setVisible(false);
                break;
                case "Titular":
                    administracionButton.setVisible(false);
                    AlumnoButton.setVisible(false);
                    InformesButton1.setVisible(false);
                    break;

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        AlumnoButton = new javax.swing.JButton();
        BoletinButton = new javax.swing.JButton();
        HorarioButton = new javax.swing.JButton();
        CuotaButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        administracionButton = new javax.swing.JButton();
        InformesButton1 = new javax.swing.JButton();
        morososButton1 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(" ");
        setBackground(new java.awt.Color(27, 28, 49));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setResizable(false);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        AlumnoButton.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        AlumnoButton.setForeground(new java.awt.Color(113, 187, 237));
        AlumnoButton.setText("Alumnos");
        AlumnoButton.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(203, 231, 250)));
        AlumnoButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AlumnoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlumnoButtonActionPerformed(evt);
            }
        });

        BoletinButton.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        BoletinButton.setForeground(new java.awt.Color(113, 187, 237));
        BoletinButton.setText("Boletín");
        BoletinButton.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(203, 231, 250)));
        BoletinButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BoletinButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoletinButtonActionPerformed(evt);
            }
        });

        HorarioButton.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        HorarioButton.setForeground(new java.awt.Color(113, 187, 237));
        HorarioButton.setText("Horarios");
        HorarioButton.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(203, 231, 250)));
        HorarioButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        HorarioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HorarioButtonActionPerformed(evt);
            }
        });

        CuotaButton.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        CuotaButton.setForeground(new java.awt.Color(113, 187, 237));
        CuotaButton.setText("Cuota");
        CuotaButton.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(203, 231, 250)));
        CuotaButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CuotaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CuotaButtonActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo 100px.png"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setForeground(new java.awt.Color(27, 28, 49));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 631, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        administracionButton.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        administracionButton.setForeground(new java.awt.Color(113, 187, 237));
        administracionButton.setText("Administracion");
        administracionButton.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(203, 231, 250)));
        administracionButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        administracionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                administracionButtonActionPerformed(evt);
            }
        });

        InformesButton1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        InformesButton1.setForeground(new java.awt.Color(113, 187, 237));
        InformesButton1.setText("Informes de pago");
        InformesButton1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(203, 231, 250)));
        InformesButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        InformesButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InformesButton1ActionPerformed(evt);
            }
        });

        morososButton1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        morososButton1.setForeground(new java.awt.Color(113, 187, 237));
        morososButton1.setText("Alumnos morosos");
        morososButton1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(203, 231, 250)));
        morososButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        morososButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                morososButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(InformesButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CuotaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(administracionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HorarioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BoletinButton, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AlumnoButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(morososButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel1)
                .addGap(53, 53, 53)
                .addComponent(AlumnoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BoletinButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(HorarioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CuotaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(InformesButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(morososButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(administracionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AlumnoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlumnoButtonActionPerformed
        ListadoAlumnos listadoAlumnos = new ListadoAlumnos(usuario.getId(), estudianteRepository, cursoRepository, titularRepository, materiaRepository, usuarioRepository);
    }//GEN-LAST:event_AlumnoButtonActionPerformed

    private void BoletinButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoletinButtonActionPerformed
        Boletin boletin = new Boletin(usuario.getId(), usuarioRepository);
    }//GEN-LAST:event_BoletinButtonActionPerformed

    private void HorarioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HorarioButtonActionPerformed
        Horarios horarios = new Horarios(usuario.getId(), usuarioRepository);
    }//GEN-LAST:event_HorarioButtonActionPerformed

    private void CuotaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CuotaButtonActionPerformed
        Pagos pagos = new Pagos(usuario.getId(), pagoRepository, usuarioRepository);
    }//GEN-LAST:event_CuotaButtonActionPerformed

    private void administracionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_administracionButtonActionPerformed
        Administracion administracion = new Administracion(cursoRepository, materiaRepository, horarioRepository, profesorRepository);
    }//GEN-LAST:event_administracionButtonActionPerformed

    private void InformesButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InformesButton1ActionPerformed
        Informes informes = new Informes(pagoRepository);
    }//GEN-LAST:event_InformesButton1ActionPerformed

    private void morososButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_morososButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_morososButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AlumnoButton;
    private javax.swing.JButton BoletinButton;
    private javax.swing.JButton CuotaButton;
    private javax.swing.JButton HorarioButton;
    private javax.swing.JButton InformesButton1;
    private javax.swing.JButton administracionButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton morososButton1;
    // End of variables declaration//GEN-END:variables
}
