/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.desktop.DesktopApp.UI;

import com.desktop.DesktopApp.Entity.UsuarioEntity;
import com.desktop.DesktopApp.Repository.*;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author Juan
 */
public class Dashboard extends javax.swing.JFrame {

    private UsuarioEntity usuario;
    private EstudianteRepository estudianteRepository;
    private ProfesorRepository profesorRepository;
    private UsuarioRepository usuarioRepository;
    private CursoRepository cursoRepository;
    private PagoRepository pagoRepository;
    private TitularRepository titularRepository;
    private MateriaRepository materiaRepository;
    private HorarioRepository horarioRepository;

    /**
     * Creates new form Dashboard
     */
    public Dashboard(UsuarioEntity usuario, EstudianteRepository estudianteRepository, ProfesorRepository profesorRepository,
                     UsuarioRepository usuarioRepository, CursoRepository cursoRepository,
                     PagoRepository pagoRepository, TitularRepository titularRepository,
                     MateriaRepository materiaRepository, HorarioRepository horarioRepository) {
        this.pagoRepository = pagoRepository;
        this.usuario = usuario;
        this.estudianteRepository = estudianteRepository;
        this.profesorRepository = profesorRepository;
        this.usuarioRepository = usuarioRepository;
        this.cursoRepository = cursoRepository;
        this.titularRepository = titularRepository;
        this.materiaRepository = materiaRepository;
        this.horarioRepository = horarioRepository;

        initComponents();
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        this.jLabel3.setText("¡Bienvenido " + usuario.getNombre().split("\\s+")[0] + "!");

        // Obtiene la resolución de pantalla actual.
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        //this.setExtendedState(this.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        int taskbarHeight = 40;
        int height = screenSize.height - taskbarHeight;
        // Establece el tamaño del JFrame al tamaño de la pantalla.
        this.setSize(screenSize.width, height);

        ocultarBotones();

        this.setVisible(true);
    }

    private void ocultarBotones() {
        switch (this.usuario.getRol().toString()) {
            case "Admin":
                CuotaButton.setVisible(false);
                BoletinButton.setVisible(false);
                HorarioButton.setVisible(false);
                break;
            case "Personal":
                BoletinButton.setVisible(false);
                HorarioButton.setVisible(false);
                break;
            case "Profesor":
                InformesButton1.setVisible(false);
                BoletinButton.setVisible(false);
                CuotaButton.setVisible(false);
                administracionButton.setVisible(false);
                morososButton.setVisible(false);
                break;
            case "Estudiante":
                administracionButton.setVisible(false);
                InformesButton1.setVisible(false);
                CuotaButton.setVisible(false);
                AlumnoButton.setVisible(false);
                morososButton.setVisible(false);
                break;
            case "Titular":
                administracionButton.setVisible(false);
                AlumnoButton.setVisible(false);
                InformesButton1.setVisible(false);
                morososButton.setVisible(false);
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        AlumnoButton = new javax.swing.JButton();
        BoletinButton = new javax.swing.JButton();
        HorarioButton = new javax.swing.JButton();
        CuotaButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        administracionButton = new javax.swing.JButton();
        InformesButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        morososButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("  ");
        setBackground(new java.awt.Color(27, 28, 49));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setResizable(false);

        jPanel3.setBackground(new java.awt.Color(13, 14, 35));

        AlumnoButton.setBackground(new java.awt.Color(49, 49, 84));
        AlumnoButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        AlumnoButton.setForeground(new java.awt.Color(204, 204, 204));
        AlumnoButton.setText("Alumnos");
        AlumnoButton.setBorder(null);
        AlumnoButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AlumnoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlumnoButtonActionPerformed(evt);
            }
        });

        BoletinButton.setBackground(new java.awt.Color(49, 49, 84));
        BoletinButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BoletinButton.setForeground(new java.awt.Color(204, 204, 204));
        BoletinButton.setText("Boletín");
        BoletinButton.setBorder(null);
        BoletinButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BoletinButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoletinButtonActionPerformed(evt);
            }
        });

        HorarioButton.setBackground(new java.awt.Color(49, 49, 84));
        HorarioButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        HorarioButton.setForeground(new java.awt.Color(204, 204, 204));
        HorarioButton.setText("Horarios");
        HorarioButton.setBorder(null);
        HorarioButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        HorarioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HorarioButtonActionPerformed(evt);
            }
        });

        CuotaButton.setBackground(new java.awt.Color(49, 49, 84));
        CuotaButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CuotaButton.setForeground(new java.awt.Color(204, 204, 204));
        CuotaButton.setText("Cuota");
        CuotaButton.setBorder(null);
        CuotaButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CuotaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CuotaButtonActionPerformed(evt);
            }
        });

        administracionButton.setBackground(new java.awt.Color(49, 49, 84));
        administracionButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        administracionButton.setForeground(new java.awt.Color(204, 204, 204));
        administracionButton.setText("Administracion");
        administracionButton.setBorder(null);
        administracionButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        administracionButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        administracionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                administracionButtonActionPerformed(evt);
            }
        });

        InformesButton1.setBackground(new java.awt.Color(49, 49, 84));
        InformesButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        InformesButton1.setForeground(new java.awt.Color(204, 204, 204));
        InformesButton1.setText("Informes de pago");
        InformesButton1.setBorder(null);
        InformesButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        InformesButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InformesButton1ActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo 100px.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(62, 62, 123));
        jLabel3.setText("Bienvenido User!");
        jLabel3.setAlignmentX(0.5F);

        morososButton.setBackground(new java.awt.Color(49, 49, 84));
        morososButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        morososButton.setForeground(new java.awt.Color(204, 204, 204));
        morososButton.setText("Alumnos morosos");
        morososButton.setBorder(null);
        morososButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        morososButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                morososButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BoletinButton, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AlumnoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CuotaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InformesButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(administracionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HorarioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(morososButton, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(15, 15, 15)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(AlumnoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(BoletinButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(HorarioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(CuotaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(InformesButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(administracionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(morososButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        jPanel1.setBackground(new java.awt.Color(27, 28, 49));
        jPanel1.setForeground(new java.awt.Color(27, 28, 49));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1004, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 761, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AlumnoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlumnoButtonActionPerformed
        ListadoAlumnos listadoAlumnos = new ListadoAlumnos(usuario.getId(), estudianteRepository, cursoRepository, titularRepository, materiaRepository, usuarioRepository);
    }//GEN-LAST:event_AlumnoButtonActionPerformed

    private void BoletinButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoletinButtonActionPerformed
        Boletin boletin = new Boletin(usuario.getId(), usuarioRepository);
    }//GEN-LAST:event_BoletinButtonActionPerformed

    private void HorarioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HorarioButtonActionPerformed
        Horarios horarios = new Horarios(usuario.getId(), usuarioRepository);
    }//GEN-LAST:event_HorarioButtonActionPerformed

    private void CuotaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CuotaButtonActionPerformed
        Pagos pagos = new Pagos(usuario.getId(), pagoRepository, usuarioRepository);
    }//GEN-LAST:event_CuotaButtonActionPerformed

    private void administracionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_administracionButtonActionPerformed
        Administracion administracion = new Administracion(cursoRepository, materiaRepository, horarioRepository, profesorRepository);
    }//GEN-LAST:event_administracionButtonActionPerformed

    private void InformesButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InformesButton1ActionPerformed
        Informes informes = new Informes(pagoRepository);
    }//GEN-LAST:event_InformesButton1ActionPerformed

    private void morososButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_morososButtonActionPerformed
        Morosos morosos = new Morosos(titularRepository);
    }//GEN-LAST:event_morososButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AlumnoButton;
    private javax.swing.JButton BoletinButton;
    private javax.swing.JButton CuotaButton;
    private javax.swing.JButton HorarioButton;
    private javax.swing.JButton InformesButton1;
    private javax.swing.JButton administracionButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton morososButton;
    // End of variables declaration//GEN-END:variables
}
